"use client";

import React from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import withAuth from "../firebase/withAuth";
import { auth } from "../../config/firebase";
import { signOut } from "firebase/auth";

export default function Homepage() {
    const router = useRouter();
    return (
        <div className="min-h-screen flex flex-col items-center justify-center">
          <head>
            <title>Homepage</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </head>
    
          <main className="flex flex-col items-center justify-center flex-1 py-5">
            <h1 className="text-4xl font-bold text-center mb-10">Homepage</h1>
            <div className="flex gap-8">
              <button className="w-48 h-32 font-bold bg-white border-2 border-black text-black text-xl rounded-lg hover:bg-gray-200" onClick={() => router.push("/input")}>
                Generate a new meal plan
              </button>
              <button className="w-48 h-32 font-bold bg-white border-2 border-black text-black text-xl rounded-lg hover:bg-gray-200" onClick={() => router.push("/savedmeals")}>
                View saved <br></br> meal plan
              </button>
            </div>
          </main>
        </div>
    );
}
